[package]
name = "amqp_test"
version = "0.1.0"
authors = ["Terry Zhao <terryzhao1981@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.40"
serde_derive = "1.0.98"
reqwest = "0.9.19"
amqp = "0.1.3"
env_logger = "0.6.2"
